### ISSUE TITLE
Adding the option to place a transaction at a specific block

### ISSUE THREAD

**Issue by davestaxcp** [jdogresorg/freewallet-desktop#154]
I have noticed users looking to use Counterparty functions at a specific Bitcoin block.

Is this possible to do on Counterparty using this: https://en.bitcoin.it/wiki/NLockTime ?

The use cases done in the past were auctions for specific XCP/TOKEN pairs and at a "specific block" the auction ended

Another use case that came up were for "scheduled burns" to happen at a specific time (specific block)

Could this be possible in the future for use on Freewallet?

**Comment by jdogresorg** [comment]
Seems more appropriate to integrate this functionality into Counterparty rather than freewallet. 

IMO Freewallet should just showcase the existing Counterparty functionality.... I dont want to get in the habit of building functionality into FreeWallet which is not a part of the counteparty core functionality.

Def see some value in being able to execute specific transactions a specific blocks, but feel nlocktime being integrated into counterparty-lib is the best path forward for this type of functionality.

Perhaps create a CIP discussion on this topic :)
