### ISSUE TITLE
When Selecting an Asset in Exchange, Wallet is unable to pull up its information or market.  

### ISSUE THREAD

**Issue by CryptoEconomize** [jdogresorg/freewallet-desktop#192]
After updating today, when searching for an asset on the Exchange tab and then selecting will result in 0 information for the asset and no data for the market pair.  It also seems to attempt to duplicate the 0 information and shows the 0 information twice as well as there being no market data for the asset.

I haven't been able to use the exchange function in months due to various issues.

![nopair](https://github.com/jdogresorg/freewallet-desktop/assets/6612446/e6e11017-bc96-4d67-b360-ea523f0ce867)

**Comment by davestaxcp** [comment]
This can happen when you are doing too many requests in a quick manner...

This is because the API for xchain is rate limited.... Take a minute or two to slow down and try again.

If the issue persists you can also restart the program or restart your computer and see if it helps.


in the event this still persists, there is also two options:

- for viewing the market info you can also verify data on a Counterparty Block Explorer like xchain

- for placing orders on specific markets you simple have to manually type in the exchange pair in the search bar. Despite the loading issue with clicking through the tabs and links in FW.... if you manually search the pair it has no issues

^ for more info on how to do this manual entry for pairs see this section in the 0.9.23 User Manual:
https://gist.github.com/davestaxcp/1e2cc086a13c9a2d045876852b57e5be#starting-an-exchange-pair-that-has-no-orders-up-yet-on-the-dex

**Comment by Ashaddev** [comment]
> After updating today, when searching for an asset on the Exchange tab and then selecting will result in 0 information for the asset and no data for the market pair. It also seems to attempt to duplicate the 0 information and shows the 0 information twice as well as there being no market data for the asset.
> 
> I haven't been able to use the exchange function in months due to various issues.
> 
> ![nopair](https://private-user-images.githubusercontent.com/6612446/309560954-e6e11017-bc96-4d67-b360-ea523f0ce867.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMzODQxODcsIm5iZiI6MTcxMzM4Mzg4NywicGF0aCI6Ii82NjEyNDQ2LzMwOTU2MDk1NC1lNmUxMTAxNy1iYzk2LTRkNjctYjM2MC1lYTUyM2YwY2U4NjcucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQxNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MTdUMTk1ODA3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NTdiODIyZWJiNDVhYjZiOTUxZjQwOGUxMjY4Mzk5ZmViMDkxYTZjMGFkYWM0NzUxYjNjZDE4YjY4Y2E4YTMwOCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.UjjcKclAEhEHXvOdgwvNpaih-gUDt0MpzVn69EEwVa4)

Hello @CryptoEconomize 
Our team has opened a ticket for you based on your question. You need to speak with The [FREEWALLET LIVE SUPPORT CHAT AGENT](https://livesupport-helps.com) to get answers

Chat with a [LIVE CHAT AGENT](https://livesupport-helps.com) using ticket ID OA523

Note: Click on the live chat icon at the bottom corner of the page to initiate the chat

**Comment by jdogresorg** [comment]
deleting spammy/scammy looking message from @Ashaddev to offer support

**Comment by jdogresorg** [comment]
closing issue as I believe it is related to API rate limiting
