### ISSUE TITLE
Order Matching Not Working Correctly on BTC / XCP Pair

### ISSUE THREAD

**Issue by CryptoEconomize** [jdogresorg/freewallet-desktop#195]
For a long time it seems that the order matching on the BTC / XCP pair hasn't been working right.  If you notice there are orders matching on both sides that never get filled.  This also seems to occur in the counterparty wallet so I am not sure where the issue is.

![freewallet](https://github.com/jdogresorg/freewallet-desktop/assets/6612446/8327d6d8-aba7-4537-b70b-f4749ef1ba60)

**Comment by jdogresorg** [comment]
This is not a flaw.. The way the counterpart decks is designed if you want to buy something using BTC on the decks you need to use FreeWallet enable auto BTC pay and leave the wallet open in order to monitor for order matches and automatically send the BTC payment before the order match expires

What you’re seeing on the people who created orders didn’t understand what they were doing. Close their wallet order matches happened. People never sent payment in time so the order matches expire.

This is not an issue with FreeWallet or even a technical issue with counterparty…. The wallet works as it is designed as the protocol…. The issue is an educational issue with users, assuming how things work, Complaining when they don’t work as expected.

I encourage you to join the FreeWallet chat room and read the FAQ, Covers all of this

https://t.me/freewallet_io

—-

Welcome to the Official Telegram for Freewallet (Developed by @jdogresorg). We don't DM, we solve issues publicly in chat.

English only chat. If you are looking for BTNS info and discussion please visit: https://t.me/BTNS420

- The official Freewallet website is https://freewallet.io/

- Freewallet Desktop is the preferred version with the most features: https://freewallet.io/#updates

- The most recent Freewallet Desktop Version is v0.9.29: https://github.com/jdogresorg/freewallet-desktop/releases

- If you need general Freewallet support or have questions please first visit:

> The Freewallet 0.9.23 User Manual/FAQ: https://github.com/jdogresorg/freewallet-desktop/discussions/138
> The Counterparty Docs: docs.counterparty.io
> The Counterparty Forums: https://forums.counterparty.io/
> the "Issues" section of the Freewallet Desktop Github: https://github.com/jdogresorg/freewallet-desktop/issues 

Please DO NOT just tag Jdog for an issue you have not researched thoroughly yourself and have not already posted in the "Issues" section of the Freewallet Github. It is important we have documentation of issues on the Github.

This space is intended for the community to help new users and be a resource to help create better FAQ's, document issues and brainstorm ideas.

- Some issues are solved easily and are heavily documented in the links mentioned above, but in some cases you may be the first to experience a bug. In this case make sure you make a detailed and thorough explanation in your post on Github of the issue so it can be tested and recreated:
https://github.com/jdogresorg/freewallet-desktop/issues

- Be nice! This project runs off of donations as do Counterparty protocol updates and is mostly supported by its users. It may be some time before someone that can help will reply! 🤓

- If you have any ideas on how to make Freewallet better, more user friendly or want to express your thoughts,  go ahead and post about it in the "Discussions" page of the Github: https://github.com/jdogresorg/freewallet-desktop/discussions

For a more general chat about the Counterparty protocol please use the Counterparty Chat: https://t.me/Counterparty_XCP

**Comment by CryptoEconomize** [comment]
Well, the reason I ask (or complain as you rudely put it) is because I've placed buy orders in that pair many times to buy via BTC and leave my wallet open and the orders never execute which was why I was asking.  I don't use telegram however.   My wallet also shows I have open orders that closed many many blocks ago but those orders just sit there in an open status in my wallet.

Anyhow, since I'm just complaining, I guess just ignore it.  LOL

**Comment by jdogresorg** [comment]
apologies if my response came across as rude or as if I am ignoring your issue.

My intent was simply to communicate that this is not an issue in the wallet, and so it is not appropriate to report the issue here, since this is for reporting issues with the wallet not working as designed.
