### ISSUE TITLE
 Counterparty API Error(s): Unknown error

### ISSUE THREAD

**Issue by swedishfrenchpress** [jdogresorg/freewallet-desktop#225]
I am getting the following error when I try to send BTC:
<img width="616" alt="image" src="https://github.com/user-attachments/assets/436b71db-41ab-4233-8388-719588e5d214">

Trouble shooting steps:
- Downloaded the latest release. 
- Turned off auto-donate
- Set APL SSL to no
- Reset defaults in server settings.

Still nothing. Any suggestions for help?

**Comment by jdogresorg** [comment]
Unfortunately this error is coming directly from the Counterparty API... notice the titlebar says "Counterparty API Error(s)"...

I felt it was important to separate the errors that freewallet throws from the errors that the Counterparty software throws, as there have been a number of updates to Counterparty over the past couple months that have caused issues.

Please try you request again... your server settings are fine, because your not getting a communication error, and instead are getting an error directly from the Counterparty API.

**Comment by jdogresorg** [comment]
Can you please post the address your trying to perform the action from (in text, so I can copy), and a screenshot of the form your trying to fill out?

I will add your address as a "watch-only" address here and try the same action and see if I get the issue... Most likely this is an issue that will need to be reported to "Counterparty 2.0 devs".... but i'll help ya out with the tech details so they actually look into the issue rather than just ignore it.

**Comment by swedishfrenchpress** [comment]
bc1q800sc3kum2vng93cwh4vrn0aja6c8uvp0c2w5ns4s0ppfs02dw0sk2wjz5

It is a legacy address generated from Phoenix. I can try to use some other wallet software to generate a legacy address.
