### ISSUE TITLE
SENDING OUT/freewallet

### ISSUE THREAD

**Issue by sampopsick** [jdogresorg/freewallet-desktop#48]
When trying so send out some crypto. it says "error server with counterparty" yesterday was working perfectly. can you please with the issue ?

**Comment by jdogresorg** [comment]
Use freewallet.io desktop and you should have no issues... There is currently no problem with any of the Counterparty servers.

**Comment by sampopsick** [comment]
Hi, I’ve been trying the desktop version. I have a MacBook but doesn’t
allow me to open it. Says something like developer haven’t confirm with
Apple or something.

**Comment by jdogresorg** [comment]
Since the app is downloaded from the internet, your Mac is trying to protect you from running apps from unknown developers, which is a good thing… you should be able to get past this issue by using these instructions below to open and run the app.

https://eshop.macsales.com/blog/51009-how-to-open-any-app-in-macos-even-if-it-doesnt-want-you-to <https://eshop.macsales.com/blog/51009-how-to-open-any-app-in-macos-even-if-it-doesnt-want-you-to>

J-Dog
***@***.***
GPG : 0C85 9EE8 BC7D 0A56 055A  6D31 2411 DE07 1B00 02BF

**Comment by sampopsick** [comment]
Hi I followed your instructions and thi is what happened. Can you please
help me ?

**Comment by sampopsick** [comment]
Hi I’ve been having problem with another transaction. It says same thing
last time
